# Database Connection
url: localhost:5432
database: id_db
user: id_project
password: id_project

# ==========================================
# 1. Screen: Reading data
# ==========================================
screen: read_functions #4F709C View Data
fun: countries Show Countries
fun: persons Show Persons
fun: person_contact_data Show Contact Data
fun: players Show Players
fun: arbiters Show Arbiters
fun: tournaments Show Tournaments
fun: chess_type Show Chess Types
fun: games Show Games
fun: live_rating Show Live Ratings
fun: rating_history Show Rating History
fun: time_controls Show Time Controls
fun: titles Show Titles
fun: players_titles Show Player Titles

# ==========================================
# 2. Screen: Inserting new data
# ==========================================
screen: insert_functions #5F8D4E Add Data
fun: noout_countries Add Country (Country Name, Continent)
fun: noout_persons Add Person (First Name, Last Name, Date of Birth, Gender, Country ID, Club ID)
fun: noout_person_contact_data Add Contact Data (Person ID, Email Address, Phone Number, Valid From, Valid To)
fun: noout_players Add Player (Person ID)
fun: noout_arbiters Add Arbiter (Person ID)
fun: noout_tournaments Add Tournament (Chess Type ID, Address, Country ID, Name, Main Arbiter ID, Time Control ID)
fun: noout_chess_type Add Chess Type (Name, Total Time From, Total Time To)
fun: noout_games Add Game (Tournament ID, White Player ID, Black Player ID, Result, Round Number, PGN Data)
fun: noout_live_rating Add Live Rating (Player ID, Chess Type ID, Rating Value)
fun: noout_rating_history Add Rating History Record (Player ID, Rating Value, Chess Type ID, Date From, Date To)
fun: noout_time_controls Add Time Control (Starting Time, Increment)
fun: noout_titles Add Title (Short Name, Full Name)
fun: noout_players_titles Add Player Title (Player ID, Title Short Name, Date Achieved, Norm 1 Tournament ID, Norm 2 Tournament ID, Norm 3 Tournament ID, Rating Norm Date)

# ==========================================
# 3. Screen: Removing data
# ==========================================
screen: remove_functions #A75D5D Delete Data
fun: noout_countries Remove Country (Country ID)
fun: noout_persons Remove Person (Person ID)
fun: noout_person_contact_data Remove Contact Data (Person ID, Timestamp From)
fun: noout_players Remove Player (Player ID)
fun: noout_arbiters Remove Arbiter (Arbiter ID)
fun: noout_tournaments Remove Tournament (Tournament ID)
fun: noout_chess_type Remove Chess Type (Chess Type ID)
fun: noout_games Remove Game (Game ID)
fun: noout_live_rating Remove Live Rating (Player ID, Chess Type ID)
fun: noout_rating_history Remove Rating History Record (Player ID, Chess Type ID, Date From)
fun: noout_time_controls Remove Time Control (Time Control ID)
fun: noout_titles Remove Title (Title Short Name)
fun: noout_players_titles Remove Player Title (Player ID, Title Short Name)
